#!/usr/bin/env python3

"""
This script generates Poincare plots for the Reiman field model.
You can run this script either serially or with mpi.
"""

import numpy as np
import sys
sys.path.append('/Users/mattland/CaryHanson')
from caryhanson import ReimanField, compute_poincare, poincare_save
from mpi4py import MPI

comm = MPI.COMM_WORLD
mpi_rank = comm.Get_rank()

rf = ReimanField()

# Define initial (R,Z) points for the Poincare plot:
r0 = np.concatenate((np.linspace(1.193, 1.1995, 4),
                     np.linspace(1.20872, 1.2276, 12)))
z0 = r0 * 0

npoints = 2000
rtol = 1e-6
atol = 1e-9
data = compute_poincare(rf, r0, z0, npoints=npoints, rmin=0.7,
                        rmax=1.3, zmin=-0.3, zmax=0.3, rtol=rtol, atol=atol)

if mpi_rank != 0:
    exit(0)

filename = 'Poincare_Reiman_rtol' + str(rtol) + '_atol' + str(atol) \
    + '_Npoints' + str(npoints) + '_Nlines' + str(len(r0)) + '.dat'
print('Saving file ', filename)
poincare_save(data, filename)
