#!/usr/bin/env python3

"""
This script generates Poincare plots for the configurations
in Hanson & Cary (1984). You can run it either serially or with mpi.
"""

from caryhanson import HelicalCoil, poincare
import numpy as np

#hc = HelicalCoil() # Straight winding law
hc = HelicalCoil.optimized() # Optimized winding law from Hanson & Cary (1984)

# Define initial (R,Z) points for the Poincare plot:
r = np.linspace(0.96, 1.13, 8)
z = r * 0

poincare(hc, r, z, npoints=200, pdf=True)
